buy_bundle:
  name: Buy Bundle
  description: Trigger a data bundle purchase for a specific Odido device.
  fields:
    device_id:
      name: Device
      description: The device to buy a bundle for.
      required: true
      selector:
        device:
          integration: odido
          domain: odido
    buying_code:
      name: Buying Code
      description: Buying code for the bundle. Defaults to A0DAY01.
      required: false
      default: A0DAY01
      selector:
        text:

